
const data = [
    {
        id: '5f7c160250a4ca6e0e1a0263',
        type: 'Delivery',
        recipient_sender_device_signature_file_url: '',
        signature_file_url: '',
        photo_1_file_url: '',
        photo_2_file_url: '',
        photo_3_file_url: '',
        photo_4_file_url: '',
        photo_5_file_url: '',
        photo_6_file_url: '',
        photo_7_file_url: '',
        photo_8_file_url: '',
        photo_9_file_url: '',
        photo_10_file_url: '',
        primary_job_status: "dispatched",
        open_to_marketplace: false,
        marketplace_offer: '',
        do_number: "KECSG0183",
        attempt: 1,
        date: 2020 - 10 - 05,
        start_date: 2020 - 10 - 05,
        job_age: 20,
        job_release_time: '',
        job_time: '',
        time_window: '',
        job_received_date: '',
        tracking_number: '',
        order_number: '',
        job_type: '',
        job_sequence: '',
        job_fee: '',
        address_lat: '',
        address_lng: '',
        address: "533, UPPER CROSS ST, #13 - 218,HONG LIM CPLX, CHINA TOWN .  050533,",
        company_name: '',
        address_1: '',
        address_2: '',
        address_3: '',
        postal_code: 050533,
        city: '',
        state: '',
        country: '',
        billing_address: '',
        deliver_to_collect_from: 'WILLIAM',
        last_name: '',
        phone_number: 88888888,
        sender_phone_number: '',
        fax_number: '',
        instructions: '',
        assign_to: '',
        notify_email: '',
        webhook_url: '',
        zone: '',
        customer: '',
        account_number: '',
        job_owner: '',
        invoice_number: '',
        invoice_amount: '',
        payment_mode: '',
        payment_amount: '',
        group_id: '5f7a8c4af7c9aa30f193eb37',
        group_name: 'KEC/Test',
        group_code: '',
        source: '',
        weight: '',
        parcel_width: '',
        parcel_length: '',
        parcel_height: '',
        cubic_meters: '',
        boxes: '',
        cartons: '',
        pieces: '',
        envelopes: '',
        pallets: '',
        bins: '',
        trays: '',
        bundles: '',
        rolls: '',
        number_of_shipping_labels: '',
        attachment_url: '',
        detrack_number: 'DET2391882746',
        status: 'dispatched',
        tracking_status: 'Info received',
        reason: '',
        received_by_sent_by: '',
        note: '',
        carrier: '',
        pod_time: '',
        pod_lat: '',
        pod_lng: '',
        pod_address: '',
        address_tracked_at: '',
        arrived_lat: '',
        arrived_lng: '',
        arrived_address: '',
        arrived_at: '',
        texted_at: '',
        called_at: '',
        serial_number: '',
        recipient_sender_device_pod_at: '',
        recipient_sender_device_signed_by: '',
        signed_at: '',
        photo_1_at: '',
        photo_2_at: '',
        photo_3_at: '',
        photo_4_at: '',
        photo_5_at: '',
        photo_6_at: '',
        photo_7_at: '',
        photo_8_at: '',
        photo_9_at: '',
        photo_10_at: '',
        actual_weight: '',
        temperature: '',
        hold_time: '',
        payment_collected: '',
        auto_reschedule: '',
        actual_crates: '',
        actual_pallets: '',
        actual_utilization: '',
        goods_service_rating: '',
        driver_rating: '',
        customer_feedback: '',
        eta_time: '',
        live_eta: '',
        depot: '',
        depot_contact: '',
        department: '',
        sales_person: '',
        identification_number: '',
        bank_prefix: '',
        run_number: '',
        head_to_delivery_at: '',
        pod_at: '',
        job_price: '',
        insurance_price: '',
        insurance_coverage: false,
        total_price: '',
        payer_type: '',
        remarks: '',
        items_count: 0,
        service_type: '',
        warehouse_address: '',
        destination_time_window: '',
        door: '',
        time_zone: '',
        created_at: '2020-10-06T15:00:38.767+08:00',
        on_demand: false,
        vehicle_type: '',
        priority: '',
        service_time: '',
        contractor_group_name: '',
        connect_token: '',
        connect_host: '',
        connect_id: '',
        job_order: '',
        tracking_status_code: 'info_recv',
        driver_mobile_number: '',
        reattempted: '',
        cubic_meter: '',
        tracking_link: 'https://trk.la/hmGJvnr',
        contactless_signature_link: 'https://trk.la/hmGJvnr?s=1',
        available_statuses: {
            info_recv: 'Info Received',
            picked_up: 'Picked Up',
            dispatched: 'In Progress',
            completed: 'Delivered',
            completed_partial: 'Partially Delivered',
            failed: 'Not Delivered',
            on_hold: 'On Hold',
            return: 'Return'
        },
        items: [],
        milestones: [
            {
                status: 'info_recv',
                assign_to: '',
                reason: '',
                pod_at: '2020-10-06T15:00:38.766+08:00',
                created_at: '2020-10-06T15:00:38.767+08:00',
                user_name: 'Susie Yao'
            }
        ]
    },
    {
        id: '5f7c160250a4ca6e0e1a0264',
        type: 'Delivery',
        recipient_sender_device_signature_file_url: '',
        signature_file_url: '',
        photo_1_file_url: '',
        photo_2_file_url: '',
        photo_3_file_url: '',
        photo_4_file_url: '',
        photo_5_file_url: '',
        photo_6_file_url: '',
        photo_7_file_url: '',
        photo_8_file_url: '',
        photo_9_file_url: '',
        photo_10_file_url: '',
        primary_job_status: 'dispatched',
        open_to_marketplace: false,
        marketplace_offer: '',
        do_number: 'KECSG0184',
        attempt: 1,
        date: 2020 - 10 - 05,
        start_date: 2020 - 10 - 05,
        job_age: 20,
        job_release_time: '',
        job_time: '*Urgent* (Must deliver on 01/8)',
        time_window: '',
        job_received_date: '',
        tracking_number: '',
        order_number: '',
        job_type: '',
        job_sequence: '',
        job_fee: '',
        address_lat: '',
        address_lng: '',
        address: 'Blk 510, Pasir Ris Street 52, #02-151, Singapore 510510',
        company_name: '',
        address_1: '',
        address_2: '',
        address_3: '',
        postal_code: '049246',
        city: '',
        state: '',
        country: '',
        billing_address: '',
        deliver_to_collect_from: 'Diyana AB',
        last_name: '',
        phone_number: 88888888,
        sender_phone_number: '',
        fax_number: '',
        instructions: '',
        assign_to: '',
        notify_email: '',
        webhook_url: '',
        zone: 'Central - CBD',
        customer: '',
        account_number: '',
        job_owner: '',
        invoice_number: '',
        invoice_amount: '',
        payment_mode: '',
        payment_amount: '',
        group_id: '5f7a8c4af7c9aa30f193eb37',
        group_name: 'KEC/Test',
        group_code: '',
        source: '',
        weight: '',
        parcel_width: '',
        parcel_length: '',
        parcel_height: '',
        cubic_meters: '',
        boxes: '',
        cartons: '',
        pieces: '',
        envelopes: '',
        pallets: '',
        bins: '',
        trays: '',
        bundles: '',
        rolls: '',
        number_of_shipping_labels: '',
        attachment_url: '',
        detrack_number: 'DET2391882747',
        status: 'dispatched',
        tracking_status: 'Info received',
        reason: '',
        received_by_sent_by: '',
        note: '',
        carrier: '',
        pod_time: '',
        pod_lat: '',
        pod_lng: '',
        pod_address: '',
        address_tracked_at: '',
        arrived_lat: '',
        arrived_lng: '',
        arrived_address: '',
        arrived_at: '',
        texted_at: '',
        called_at: '',
        serial_number: '',
        recipient_sender_device_pod_at: '',
        recipient_sender_device_signed_by: '',
        signed_at: '',
        photo_1_at: '',
        photo_2_at: '',
        photo_3_at: '',
        photo_4_at: '',
        photo_5_at: '',
        photo_6_at: '',
        photo_7_at: '',
        photo_8_at: '',
        photo_9_at: '',
        photo_10_at: '',
        actual_weight: '',
        temperature: '',
        hold_time: '',
        payment_collected: '',
        auto_reschedule: '',
        actual_crates: '',
        actual_pallets: '',
        actual_utilization: '',
        goods_service_rating: '',
        driver_rating: '',
        customer_feedback: '',
        eta_time: '',
        live_eta: '',
        depot: '',
        depot_contact: '',
        department: '',
        sales_person: '',
        identification_number: '',
        bank_prefix: '',
        run_number: '',
        head_to_delivery_at: '',
        pod_at: '',
        job_price: '',
        insurance_price: '',
        insurance_coverage: false,
        total_price: '',
        payer_type: '',
        remarks: '',
        items_count: 0,
        service_type: '',
        warehouse_address: '',
        destination_time_window: '',
        door: '',
        time_zone: '',
        created_at: 2020 - 10 - 06,
        on_demand: false,
        vehicle_type: '',
        priority: '',
        service_time: '',
        contractor_group_name: '',
        connect_token: '',
        connect_host: '',
        connect_id: '',
        job_order: '',
        tracking_status_code: 'info_recv',
        driver_mobile_number: '',
        reattempted: '',
        cubic_meter: '',
        tracking_link: 'https://trk.la/hmGJvXx',
        contactless_signature_link: 'https://trk.la/hmGJvXx?s=1',
        available_statuses: {
            info_recv: 'Info Received',
            picked_up: 'Picked Up',
            dispatched: 'In Progress',
            completed: 'Delivered',
            completed_partial: 'Partially Delivered',
            failed: 'Not Delivered',
            on_hold: 'On Hold',
            return: 'Return'
        },
        items: [],
        milestones: [
            {
                status: 'info_recv',
                assign_to: '',
                reason: '',
                pod_at: 2020 - 10 - 06,
                created_at: 2020 - 10 - 05,
                user_name: 'Susie Yao'
            }
        ]
    }
]

module.exports = data