const mongoose = require('mongoose')

const deliveriesSchema = new mongoose.Schema({

    id: String,
    type: String,
    recipient_sender_device_signature_file_url: String,
    signature_file_url: String,
    photo_1_file_url: String,
    photo_2_file_url: String,
    photo_3_file_url: String,
    photo_4_file_url: String,
    photo_5_file_url: String,
    photo_6_file_url: String,
    photo_7_file_url: String,
    photo_8_file_url: String,
    photo_9_file_url: String,
    photo_10_file_url: String,
    primary_job_status: String,
    open_to_marketplace: Boolean,
    marketplace_offer: String,
    do_number: String,
    attempt: Number,
    date: Date,
    start_date: Date,
    job_age: Number,
    job_release_time: String,
    job_time: String,
    time_window: String,
    job_received_date: String,
    tracking_number: String,
    order_number: String,
    job_type: String,
    job_sequence: String,
    job_fee: String,
    address_lat: String,
    address_lng: String,
    address: String,
    company_name: String,
    st_address_1: String,
    address_2: String,
    address_3: String,
    st_zip: String,
    city: String,
    state: String,
    country: String,
    billing_address: String,
    deliver_to_collect_from: String,
    last_name: String,
    phone_number: Number,
    sender_phone_number: String,
    fax_number: String,
    instructions: String,
    assign_to: String,
    notify_email: String,
    webhook_url: String,
    zone: String,
    customer: String,
    account_number: String,
    job_owner: String,
    invoice_number: String,
    invoice_amount: String,
    payment_mode: String,
    payment_amount: String,
    group_id: String,
    group_name: String,
    group_code: String,
    source: String,
    weight: String,
    parcel_width: String,
    parcel_length: String,
    parcel_height: String,
    cubic_meters: String,
    boxes: String,
    cartons: String,
    pieces: String,
    envelopes: String,
    pallets: String,
    bins: String,
    trays: String,
    bundles: String,
    rolls: String,
    number_of_shipping_labels: String,
    attachment_url: String,
    detrack_number: String,
    status: String,
    tracking_status: String,
    reason: String,
    received_by_sent_by: String,
    note: String,
    carrier: String,
    pod_time: String,
    pod_lat: String,
    pod_lng: String,
    pod_address: String,
    address_tracked_at: String,
    arrived_lat: String,
    arrived_lng: String,
    arrived_address: String,
    arrived_at: String,
    texted_at: String,
    called_at: String,
    serial_number: String,
    recipient_sender_device_pod_at: String,
    recipient_sender_device_signed_by: String,
    signed_at: String,
    photo_1_at: String,
    photo_2_at: String,
    photo_3_at: String,
    photo_4_at: String,
    photo_5_at: String,
    photo_6_at: String,
    photo_7_at: String,
    photo_8_at: String,
    photo_9_at: String,
    photo_10_at: String,
    actual_weight: String,
    temperature: String,
    hold_time: String,
    payment_collected: String,
    auto_reschedule: String,
    actual_crates: String,
    actual_pallets: String,
    actual_utilization: String,
    goods_service_rating: String,
    driver_rating: String,
    customer_feedback: String,
    eta_time: String,
    live_eta: String,
    depot: String,
    depot_contact: String,
    department: String,
    sales_person: String,
    identification_number: String,
    bank_prefix: String,
    run_number: String,
    head_to_delivery_at: String,
    pod_at: String,
    job_price: String,
    insurance_price: String,
    insurance_coverage: Boolean,
    total_price: String,
    payer_type: String,
    remarks: String,
    items_count: Number,
    service_type: String,
    warehouse_address: String,
    destination_time_window: String,
    door: String,
    time_zone: String,
    created_at: Date,
    on_demand: Boolean,
    vehicle_type: String,
    priority: String,
    service_time: String,
    contractor_group_name: String,
    connect_token: String,
    connect_host: String,
    connect_id: String,
    job_order: String,
    tracking_status_code: String,
    driver_mobile_number: String,
    reattempted: String,
    cubic_meter: String,
    tracking_link: String,
    contactless_signature_link: String,
    available_statuses: {
        info_recv: String,
        picked_up: String,
        dispatched: String,
        completed: String,
        completed_partial: String,
        failed: String,
        on_hold: String,
        return: String
    },
    items: [],
    milestones: [
        {
            status: String,
            assign_to: String,
            reason: String,
            pod_at: String,
            created_at: String,
            user_name: String
        }
    ]
})

const DeliveriesModel = mongoose.model('deliveries', deliveriesSchema)

module.exports = DeliveriesModel








